name: kConnect
version: 1.0
main: eu.kuubik.kConnect.kConnect
api-version: 1.16
description: This plugin generates an code for user to insert it in kuubik.eu website to connect their accounts.
author: kqrmo
website: https://karmotutk.eu/

commands:
  kc:
    description: kConnect plugins main command.
    usage: /kc [reload/info/help/author]
    permission: kconnect.kconnect
    permission-message: Sul ei ole <permission> õigust..
  genereeri:
    description: Genereerib sulle koodi, mis kodulehel sisestada.
    usage: /genereeri